# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "BollingerBands",
    "ChartSeries",
    "VolumeBars",
    "bollinger_bands",
    "ema",
    "rsi",
    "sma",
    "volume_bars",
]

@typing.final
class BollingerBands:
    r"""
    Bollinger middle, upper, and lower bands aligned with input closes.
    """
    @property
    def middle(self) -> ChartSeries:
        r"""
        Rolling arithmetic mean.
        """
    @property
    def upper(self) -> ChartSeries:
        r"""
        Middle plus population standard deviation times the multiplier.
        """
    @property
    def lower(self) -> ChartSeries:
        r"""
        Middle minus population standard deviation times the multiplier.
        """

@typing.final
class ChartSeries:
    r"""
    Values aligned with input bars. Entries before `first_valid` are warmup slots.
    """
    @property
    def values(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        A float64 copy of all bars; warmup slots contain zero placeholders.
        """
    @property
    def first_valid(self) -> builtins.int:
        r"""
        Index of the first usable result, or the series length if none is usable.
        """
    def to_list(self) -> builtins.list[typing.Optional[builtins.float]]:
        r"""
        Copy values with `None` in warmup slots for JSON or chart libraries.
        """

@typing.final
class VolumeBars:
    r"""
    Raw volume and the per-bar direction relative to the open.
    """
    @property
    def volume(self) -> ChartSeries:
        r"""
        Raw nonnegative volume, aligned with input bars.
        """
    @property
    def direction(self) -> numpy.typing.NDArray[numpy.int8]:
        r"""
        Per-bar direction: -1 for down, 0 for flat, 1 for up.
        """

def bollinger_bands(close: typing.Sequence[builtins.float], period: builtins.int = 20, multiplier: builtins.float = 2.0) -> BollingerBands:
    r"""
    Bollinger bands using a population standard deviation over each window.
    """

def ema(close: typing.Sequence[builtins.float], period: builtins.int) -> ChartSeries:
    r"""
    Exponential moving average seeded by the first `period`-bar SMA.
    """

def rsi(close: typing.Sequence[builtins.float], period: builtins.int = 14) -> ChartSeries:
    r"""
    Wilder RSI, seeded after `period` closing-price changes.
    """

def sma(close: typing.Sequence[builtins.float], period: builtins.int) -> ChartSeries:
    r"""
    Simple moving average, seeded after `period` closing prices.
    """

def volume_bars(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], volume: typing.Sequence[builtins.float]) -> VolumeBars:
    r"""
    Validate OHLCV bars and return raw volume with close-versus-open direction.
    """
