#ifndef ITOFIN_H
#define ITOFIN_H

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
typedef double Real;

#define INVALID_ARGUMENT 1

#define INVALID_HANDLE 2

#define CORE_ERROR 3

#define WRONG_THREAD 4

#define PANIC 5

#define POISONED 6

/**
 * Opaque thread-confined owner of live native objects. Never copy this value.
 */
typedef struct Context Context;

/**
 * Caller-owned error. Zero code means success; message is NUL-terminated UTF-8.
 */
typedef struct ItofinError {
  int32_t code;
  char message[1024];
} ItofinError;

/**
 * GBM inputs; arrays each contain `assets` doubles, correlation `assets*assets`.
 */
typedef struct ItofinGbmInput {
  const Real *initial;
  const Real *drift;
  const Real *volatility;
  const Real *correlation;
  size_t assets;
  Real horizon;
  size_t steps;
  size_t paths;
  uint32_t seed;
  /**
   * 0: full path/time/asset output; 1: terminal path/asset output.
   */
  int32_t terminal_only;
} ItofinGbmInput;

typedef struct ItofinDateParts {
  int32_t day;
  int32_t month;
  int32_t year;
} ItofinDateParts;

typedef struct ItofinScheduleConfig {
  int32_t start;
  int32_t end;
  int32_t frequency;
  uint64_t calendar;
  int32_t convention;
  int32_t rule;
  /**
   * -1 uses convention.
   */
  int32_t termination_convention;
} ItofinScheduleConfig;

typedef struct ItofinResultsFields {
  Real npv;
  Real error_estimate;
  int32_t valuation_date;
  uint8_t has_npv;
  uint8_t has_error_estimate;
  uint8_t has_valuation_date;
  size_t additional_count;
} ItofinResultsFields;

typedef struct ItofinIborConfig {
  int32_t tenor_length;
  int32_t tenor_unit;
  uint32_t settlement_days;
  uint64_t currency;
  uint64_t fixing_calendar;
  uint64_t value_calendar;
  uint64_t maturity_calendar;
  int32_t convention;
  bool end_of_month;
  uint64_t day_counter;
  uint64_t forwarding;
  uint64_t settings;
} ItofinIborConfig;

typedef struct ItofinIborInfo {
  int32_t tenor_length;
  int32_t tenor_unit;
  int32_t convention;
  bool end_of_month;
} ItofinIborInfo;

/**
 * quote/settings zero select scalar volatility/fixed date respectively.
 */
typedef struct ItofinConstantRateVolConfig {
  int32_t reference_date;
  uint32_t settlement_days;
  uint64_t calendar;
  int32_t convention;
  double volatility;
  uint64_t day_counter;
  int32_t volatility_type;
  double shift;
  uint64_t quote;
  uint64_t settings;
} ItofinConstantRateVolConfig;

/**
 * Scalar market inputs followed by native Heston parameters.
 */
typedef struct HestonProcessConfig {
  double risk_free_rate;
  double dividend_yield;
  double spot;
  double v0;
  double kappa;
  double theta;
  double sigma;
  double rho;
  int32_t reference_date;
  uint64_t day_counter;
} HestonProcessConfig;

/**
 * Presence flags distinguish omitted criteria from explicit zero values.
 */
typedef struct EndCriteriaConfig {
  size_t max_iterations;
  size_t stationary_iterations;
  double root_epsilon;
  double function_epsilon;
  double gradient_epsilon;
  int32_t has_stationary;
  int32_t has_gradient;
} EndCriteriaConfig;

/**
 * Maturity is a value (length, Python TimeUnit discriminant).
 */
typedef struct HestonHelperConfig {
  int32_t maturity_length;
  int32_t maturity_unit;
  uint64_t calendar;
  double spot;
  double strike;
  double volatility;
  double risk_free_rate;
  double dividend_yield;
  int32_t error_type;
  int32_t reference_date;
  uint64_t day_counter;
  uint64_t settings;
} HestonHelperConfig;

typedef struct SwaptionHelperConfig {
  int32_t maturity_length;
  int32_t maturity_unit;
  int32_t length;
  int32_t length_unit;
  double volatility;
  uint64_t index;
  int32_t fixed_tenor_length;
  int32_t fixed_tenor_unit;
  uint64_t fixed_day_counter;
  uint64_t floating_day_counter;
  uint64_t curve;
  int32_t error_type;
  double nominal;
} SwaptionHelperConfig;

/**
 * Presence bits: steps=1, steps/year=2, samples=4, tolerance=8, max_samples=16,
 * seed=32, antithetic=64, polynomial_order=128, calibration_samples=256.
 */
typedef struct McConfig {
  uint32_t present;
  size_t steps;
  size_t steps_per_year;
  size_t samples;
  double absolute_tolerance;
  size_t max_samples;
  uint32_t seed;
  int32_t antithetic;
  size_t polynomial_order;
  size_t calibration_samples;
} McConfig;

/**
 * A zero quote handle selects `rate`; a nonzero settings handle selects moving dates.
 */
typedef struct ItofinFlatHazardConfig {
  int32_t reference_date;
  uint32_t settlement_days;
  uint64_t calendar;
  uint64_t quote;
  double rate;
  uint64_t day_counter;
  uint64_t settings;
} ItofinFlatHazardConfig;

typedef struct ItofinCreditNode {
  int32_t date;
  double time;
  double rate;
} ItofinCreditNode;

typedef struct ItofinSpreadCdsConfig {
  uint64_t quote;
  int32_t tenor_length;
  int32_t tenor_unit;
  int32_t settlement_days;
  uint64_t calendar;
  int32_t frequency;
  int32_t convention;
  int32_t rule;
  uint64_t day_counter;
  double recovery;
  uint64_t discount;
  uint64_t settings;
} ItofinSpreadCdsConfig;

/**
 * kind 0 = midpoint, 1 = ISDA. Fidelity enums follow Python declaration order.
 */
typedef struct ItofinCdsEngineConfig {
  uint64_t probability;
  uint64_t discount;
  uint64_t settings;
  double recovery;
  int32_t kind;
  int32_t numerical_fix;
  int32_t accrual_bias;
  int32_t forwards;
} ItofinCdsEngineConfig;

typedef struct ItofinCdsConfig {
  int32_t side;
  double notional;
  double spread;
  uint64_t schedule;
  int32_t convention;
  uint64_t day_counter;
  uint64_t settings;
  int32_t protection_start;
  int32_t settles_accrual;
  int32_t pays_at_default_time;
  int32_t rebates_accrual;
} ItofinCdsConfig;

typedef struct ItofinMakeCdsConfig {
  int32_t term_date;
  double running_spread;
  uint64_t settings;
  double nominal;
  double upfront;
  int32_t has_upfront;
  int32_t side;
  int32_t trade_date;
} ItofinMakeCdsConfig;

typedef struct ItofinSwapHelperConfig {
  uint64_t quote;
  int32_t tenor_length;
  int32_t tenor_unit;
  uint64_t calendar;
  int32_t frequency;
  int32_t convention;
  uint64_t day_counter;
  uint64_t index;
} ItofinSwapHelperConfig;

typedef struct ItofinFraHelperConfig {
  uint64_t quote;
  double rate;
  int32_t start_length;
  int32_t start_unit;
  uint32_t months;
  int32_t start_date;
  int32_t end_date;
  uint64_t index;
  bool indexed;
  int32_t pillar;
} ItofinFraHelperConfig;

typedef struct ItofinFuturesHelperConfig {
  uint64_t price;
  int32_t start_date;
  int32_t end_date;
  bool has_end_date;
  uint32_t months;
  uint64_t calendar;
  int32_t convention;
  bool end_of_month;
  uint64_t day_counter;
  uint64_t convexity;
  int32_t futures_type;
  uint64_t index;
} ItofinFuturesHelperConfig;

typedef struct ItofinOisHelperConfig {
  uint32_t settlement_days;
  int32_t tenor_length;
  int32_t tenor_unit;
  uint64_t quote;
  uint64_t index;
  int32_t payment_lag;
  int32_t convention;
  int32_t frequency;
  int32_t forward_length;
  int32_t forward_unit;
  uint64_t settings;
  uint64_t discounting;
  uint64_t spread;
  int32_t pillar;
  int32_t averaging;
} ItofinOisHelperConfig;

typedef struct ItofinBondHelperConfig {
  uint64_t price;
  uint32_t settlement_days;
  double face_amount;
  uint64_t schedule;
  uint64_t day_counter;
  int32_t convention;
  double redemption;
  int32_t price_type;
  uint64_t settings;
  int32_t issue_date;
  bool has_issue_date;
} ItofinBondHelperConfig;

typedef struct ItofinVolGridConfig {
  int32_t reference_date;
  uint32_t settlement_days;
  uint64_t calendar;
  int32_t convention;
  uint64_t day_counter;
  uint64_t settings;
  const int32_t *option_lengths;
  const int32_t *option_units;
  size_t rows;
  const int32_t *swap_lengths;
  const int32_t *swap_units;
  const double *strikes;
  size_t columns;
  const double *values;
  const uint64_t *quotes;
  size_t count;
  const double *shifts;
  size_t shift_count;
  int32_t volatility_type;
  int32_t flat_extrapolation;
} ItofinVolGridConfig;

typedef struct ItofinVanillaSwapConfig {
  int32_t swap_type;
  Real nominal;
  uint64_t fixed_schedule;
  Real fixed_rate;
  uint64_t fixed_day_counter;
  uint64_t floating_schedule;
  uint64_t index;
  Real spread;
  uint64_t floating_day_counter;
  uint64_t settings;
} ItofinVanillaSwapConfig;

/**
 * Optional fields are selected by bits: rate=1, effective=2, nominal=4,
 * fixed tenor=8, day counter=16, payment lag=32, discount=64, averaging=128.
 */
typedef struct ItofinMakeSwapConfig {
  int32_t tenor_length;
  int32_t tenor_unit;
  uint64_t index;
  uint64_t settings;
  uint32_t flags;
  Real fixed_rate;
  int32_t forward_length;
  int32_t forward_unit;
  int32_t effective_date;
  Real nominal;
  int32_t fixed_length;
  int32_t fixed_unit;
  uint64_t fixed_day_counter;
  int32_t payment_lag;
  uint64_t discount;
  int32_t averaging;
} ItofinMakeSwapConfig;

typedef struct ItofinFraConfig {
  uint64_t index;
  int32_t value_date;
  /**
   * Zero derives the index maturity.
   */
  int32_t maturity_date;
  int32_t position;
  Real strike;
  Real notional;
  uint64_t discount;
} ItofinFraConfig;

/**
 * ABI major version. Increment for incompatible layouts or calling conventions.
 */
uint32_t itofin_abi_version(void);

/**
 * # Safety
 * `out` must be writable. Destroy the returned context on this same thread.
 */
int32_t itofin_context_new(struct Context **out, struct ItofinError *error);

/**
 * Destroy the context and every remaining object, including a poisoned context.
 * # Safety
 * `ctx` must be a live context created here, on its owner thread, with no active calls.
 */
int32_t itofin_context_free(struct Context *ctx, struct ItofinError *error);

/**
 * Release one external reference; dependent native objects retain their references.
 * # Safety
 * Follow the crate-level context and pointer contract.
 */
int32_t itofin_handle_release(struct Context *ctx, uint64_t handle, struct ItofinError *error);

/**
 * Generate `count` standard normal values with a deterministic nonzero seed.
 * # Safety
 * Follow the crate-level pointer contract. Output contains `count` doubles.
 */
int32_t itofin_gaussian_draws(size_t count,
                              uint32_t seed,
                              Real *out,
                              size_t capacity,
                              struct ItofinError *error);

/**
 * Generate correlated GBM paths, including initial values in full-path mode.
 * # Safety
 * Input arrays and output obey the crate-level pointer/non-overlap contract.
 * Full capacity is paths*(steps+1)*assets; terminal capacity is paths*assets.
 */
int32_t itofin_gbm_paths(const struct ItofinGbmInput *input,
                         Real *out,
                         size_t capacity,
                         struct ItofinError *error);

int32_t itofin_date_new(int32_t day,
                        int32_t month,
                        int32_t year,
                        int32_t *out,
                        struct ItofinError *error);

int32_t itofin_date_parts(int32_t serial, struct ItofinDateParts *out, struct ItofinError *error);

int32_t itofin_date_shift(int32_t serial, int64_t days, int32_t *out, struct ItofinError *error);

int32_t itofin_is_imm_date(int32_t serial,
                           uint8_t main_cycle,
                           uint8_t *out,
                           struct ItofinError *error);

int32_t itofin_next_imm_date(int32_t serial,
                             uint8_t main_cycle,
                             int32_t *out,
                             struct ItofinError *error);

int32_t itofin_day_counter_new(struct Context *ctx,
                               int32_t kind,
                               uint64_t *out,
                               struct ItofinError *error);

int32_t itofin_day_counter_year_fraction(struct Context *ctx,
                                         uint64_t id,
                                         int32_t start,
                                         int32_t end,
                                         double *out,
                                         struct ItofinError *error);

/**
 * UTF-8 bytes without a trailing NUL. Query required length with capacity zero.
 */
int32_t itofin_time_name(struct Context *ctx,
                         uint64_t id,
                         int32_t kind,
                         uint8_t *out,
                         size_t capacity,
                         size_t *required,
                         struct ItofinError *error);

int32_t itofin_calendar_new(struct Context *ctx,
                            int32_t kind,
                            uint64_t *out,
                            struct ItofinError *error);

int32_t itofin_calendar_adjust(struct Context *ctx,
                               uint64_t id,
                               int32_t serial,
                               int32_t rule,
                               int32_t *out,
                               struct ItofinError *error);

int32_t itofin_calendar_advance(struct Context *ctx,
                                uint64_t id,
                                int32_t serial,
                                int32_t n,
                                int32_t unit,
                                int32_t rule,
                                uint8_t eom,
                                int32_t *out,
                                struct ItofinError *error);

int32_t itofin_schedule_new(struct Context *ctx,
                            struct ItofinScheduleConfig config,
                            uint64_t *out,
                            struct ItofinError *error);

int32_t itofin_schedule_dates(struct Context *ctx,
                              uint64_t id,
                              int32_t *out,
                              size_t capacity,
                              size_t *required,
                              struct ItofinError *error);

int32_t itofin_settings_new(struct Context *ctx, uint64_t *out, struct ItofinError *error);

int32_t itofin_settings_set_evaluation_date(struct Context *ctx,
                                            uint64_t id,
                                            int32_t serial,
                                            struct ItofinError *error);

/**
 * -1 means unset, 0 means exclude, 1 means include.
 */
int32_t itofin_settings_set_include_todays_cash_flows(struct Context *ctx,
                                                      uint64_t id,
                                                      int32_t value,
                                                      struct ItofinError *error);

int32_t itofin_settings_include_todays_cash_flows(struct Context *ctx,
                                                  uint64_t id,
                                                  int32_t *out,
                                                  struct ItofinError *error);

int32_t itofin_results_fields(struct Context *ctx,
                              uint64_t id,
                              struct ItofinResultsFields *out,
                              struct ItofinError *error);

/**
 * Read a sorted additional-results entry; key is UTF-8 without a trailing NUL.
 * Capacity zero queries the required size and still returns the real value.
 */
int32_t itofin_results_additional(struct Context *ctx,
                                  uint64_t id,
                                  size_t index,
                                  uint8_t *key,
                                  size_t capacity,
                                  size_t *required,
                                  Real *value,
                                  struct ItofinError *error);

int32_t itofin_quote_new(struct Context *ctx,
                         double value,
                         uint64_t *out,
                         struct ItofinError *error);

int32_t itofin_quote_value(struct Context *ctx,
                           uint64_t id,
                           double *out,
                           struct ItofinError *error);

int32_t itofin_quote_set(struct Context *ctx, uint64_t id, double value, struct ItofinError *error);

int32_t itofin_black_scholes_new(struct Context *ctx,
                                 double spot,
                                 double risk_free,
                                 double dividend,
                                 double volatility,
                                 int32_t reference,
                                 uint64_t dc,
                                 uint64_t *out,
                                 struct ItofinError *error);

int32_t itofin_black_scholes_from_curves(struct Context *ctx,
                                         double spot,
                                         uint64_t risk_free,
                                         uint64_t dividend,
                                         uint64_t volatility,
                                         uint64_t *out,
                                         struct ItofinError *error);

int32_t itofin_black_scholes_rate(struct Context *ctx,
                                  uint64_t id,
                                  bool dividend,
                                  double *out,
                                  struct ItofinError *error);

int32_t itofin_flat_forward_new(struct Context *ctx,
                                int32_t reference,
                                double rate,
                                uint64_t dc,
                                uint64_t *out,
                                struct ItofinError *error);

/**
 * kind: 0 linear zero, 1 cubic zero, 2 log-linear discount, 3 cubic discount, 4 backward-flat forward.
 */
int32_t itofin_node_curve_new(struct Context *ctx,
                              int32_t kind,
                              const int32_t *dates,
                              const double *values,
                              size_t len,
                              uint64_t dc,
                              uint64_t cal,
                              uint64_t *out,
                              struct ItofinError *error);

/**
 * Query: 0 discount(time), 1 discount(date), 2 zero rate, 3 forward rate.
 */
int32_t itofin_curve_value(struct Context *ctx,
                           uint64_t id,
                           int32_t query,
                           double t1,
                           double t2,
                           int32_t serial,
                           bool extrapolate,
                           double *out,
                           struct ItofinError *error);

/**
 * Query: 0 reference date, 1 maximum date, 2 extrapolation enabled.
 */
int32_t itofin_curve_info(struct Context *ctx,
                          uint64_t id,
                          int32_t query,
                          int32_t *out,
                          struct ItofinError *error);

int32_t itofin_curve_extrapolation(struct Context *ctx,
                                   uint64_t id,
                                   bool enabled,
                                   struct ItofinError *error);

/**
 * kind: discount log-linear/linear/cubic = 0/1/2, zero linear/cubic = 3/4,
 * forward linear/convex-monotone/backward-flat = 5/6/7. Algorithm: iterative/global/local = 0/1/2.
 */
int32_t itofin_piecewise_curve_new(struct Context *ctx,
                                   int32_t reference,
                                   const uint64_t *helpers,
                                   size_t len,
                                   uint64_t dc,
                                   int32_t kind,
                                   int32_t algorithm,
                                   const uint64_t *additional,
                                   size_t additional_len,
                                   uint64_t *out,
                                   struct ItofinError *error);

/**
 * Caller first queries length with capacity=0; then supplies both arrays with that capacity.
 */
int32_t itofin_curve_nodes(struct Context *ctx,
                           uint64_t id,
                           int32_t *dates,
                           double *values,
                           size_t capacity,
                           size_t *length,
                           struct ItofinError *error);

int32_t itofin_currency_new(struct Context *ctx,
                            int32_t kind,
                            uint64_t *out,
                            struct ItofinError *error);

/**
 * Fixed-size output containing the three ASCII ISO currency letters and a NUL byte.
 */
int32_t itofin_currency_code(struct Context *ctx,
                             uint64_t id,
                             uint8_t *out,
                             size_t capacity,
                             struct ItofinError *error);

/**
 * Family: 0 Euribor, 1 USD Libor, 2 JPY Libor, 3 GBP Libor, 4 EUR Libor.
 */
int32_t itofin_ibor_family_new(struct Context *ctx,
                               int32_t family,
                               int32_t length,
                               int32_t unit,
                               uint64_t forwarding,
                               uint64_t settings_id,
                               uint64_t *out,
                               struct ItofinError *error);

/**
 * custom=true uses distinct fixing/value/maturity calendars.
 */
int32_t itofin_ibor_new(struct Context *ctx,
                        const uint8_t *name,
                        size_t name_len,
                        const struct ItofinIborConfig *cfg,
                        bool custom,
                        uint64_t *out,
                        struct ItofinError *error);

int32_t itofin_estr_new(struct Context *ctx,
                        uint64_t forwarding,
                        uint64_t settings_id,
                        uint64_t *out,
                        struct ItofinError *error);

int32_t itofin_index_fixing(struct Context *ctx,
                            uint64_t id,
                            bool overnight,
                            int32_t serial,
                            bool forecast_today,
                            double *out,
                            struct ItofinError *error);

/**
 * Query 0 value date; 1 fixing date; 2 maturity date.
 */
int32_t itofin_ibor_date(struct Context *ctx,
                         uint64_t id,
                         int32_t query,
                         int32_t serial,
                         int32_t *out,
                         struct ItofinError *error);

/**
 * Query 0 day counter; 1 fixing calendar; 2 currency. Output is a newly owned handle.
 */
int32_t itofin_ibor_component(struct Context *ctx,
                              uint64_t id,
                              int32_t query,
                              uint64_t *out,
                              struct ItofinError *error);

int32_t itofin_ibor_info(struct Context *ctx,
                         uint64_t id,
                         struct ItofinIborInfo *out,
                         struct ItofinError *error);

/**
 * UTF-8, caller-owned buffer; first query capacity=0 to obtain length excluding NUL.
 */
int32_t itofin_ibor_name(struct Context *ctx,
                         uint64_t id,
                         uint8_t *out,
                         size_t capacity,
                         size_t *length,
                         struct ItofinError *error);

int32_t itofin_black_constant_vol_new(struct Context *ctx,
                                      int32_t reference_date,
                                      double volatility,
                                      uint64_t dc,
                                      uint64_t cal,
                                      uint64_t *out,
                                      struct ItofinError *error);

int32_t itofin_black_variance_curve_new(struct Context *ctx,
                                        int32_t reference_date,
                                        const int32_t *dates,
                                        const double *vols,
                                        size_t count,
                                        uint64_t dc,
                                        int32_t monotone,
                                        int32_t extrapolation,
                                        uint64_t *out,
                                        struct ItofinError *error);

int32_t itofin_black_variance_surface_new(struct Context *ctx,
                                          int32_t reference_date,
                                          const int32_t *dates,
                                          size_t date_count,
                                          const double *strikes,
                                          size_t strike_count,
                                          const double *vols,
                                          size_t vol_count,
                                          uint64_t dc,
                                          uint64_t cal,
                                          uint64_t *out,
                                          struct ItofinError *error);

/**
 * Query kind: 0 vol, 1 variance, 2 forward vol, 3 forward variance,
 * 4 minimum strike, 5 maximum strike. Times are year fractions.
 */
int32_t itofin_black_vol_query(struct Context *ctx,
                               uint64_t id,
                               int32_t kind,
                               double t1,
                               double t2,
                               double strike,
                               int32_t extrapolate,
                               double *out,
                               struct ItofinError *error);

/**
 * Date query kind: 0 vol, 1 variance.
 */
int32_t itofin_black_vol_date_query(struct Context *ctx,
                                    uint64_t id,
                                    int32_t kind,
                                    int32_t serial,
                                    double strike,
                                    int32_t extrapolate,
                                    double *out,
                                    struct ItofinError *error);

/**
 * Metadata action: 0 max date, 1 allows extrapolation, 2 enable, 3 disable.
 */
int32_t itofin_black_vol_control(struct Context *ctx,
                                 uint64_t id,
                                 int32_t action,
                                 int32_t *out,
                                 struct ItofinError *error);

int32_t itofin_sabr_smile_new(struct Context *ctx,
                              double exercise_time,
                              double forward,
                              double alpha,
                              double beta,
                              double nu,
                              double rho,
                              double shift,
                              int32_t kind,
                              uint64_t *out,
                              struct ItofinError *error);

/**
 * Query: 0 volatility, 1 variance, 2 exercise time, 3 ATM, 4 alpha, 5 beta, 6 nu, 7 rho.
 */
int32_t itofin_sabr_smile_query(struct Context *ctx,
                                uint64_t id,
                                int32_t kind,
                                double strike,
                                double *out,
                                struct ItofinError *error);

int32_t itofin_constant_swaption_vol_new(struct Context *ctx,
                                         const struct ItofinConstantRateVolConfig *cfg,
                                         uint64_t *out,
                                         struct ItofinError *error);

int32_t itofin_constant_optionlet_vol_new(struct Context *ctx,
                                          const struct ItofinConstantRateVolConfig *cfg,
                                          uint64_t *out,
                                          struct ItofinError *error);

/**
 * Swaption query: 0 volatility, 1 variance, 2 date shift.
 */
int32_t itofin_swaption_vol_query(struct Context *ctx,
                                  uint64_t id,
                                  int32_t kind,
                                  int32_t option_length,
                                  int32_t option_unit,
                                  int32_t swap_length,
                                  int32_t swap_unit,
                                  int32_t serial,
                                  double length,
                                  double strike,
                                  int32_t extrapolate,
                                  double *out,
                                  struct ItofinError *error);

/**
 * Optionlet query: 0 tenor volatility, 1 tenor variance, 2 date volatility, 3 displacement.
 */
int32_t itofin_optionlet_vol_query(struct Context *ctx,
                                   uint64_t id,
                                   int32_t kind,
                                   int32_t length,
                                   int32_t unit,
                                   int32_t serial,
                                   double strike,
                                   int32_t extrapolate,
                                   double *out,
                                   struct ItofinError *error);

/**
 * Family 0 swaption, 1 optionlet. Action: 0 reference date, 1 extrapolation state, 2 enable, 3 disable.
 */
int32_t itofin_rate_vol_control(struct Context *ctx,
                                uint64_t id,
                                int32_t family,
                                int32_t action,
                                int32_t *out,
                                struct ItofinError *error);

/**
 * `american`: 0 European, 1 American; earliest ignored for European exercise.
 */
int32_t itofin_option_new(struct Context *ctx,
                          int32_t kind,
                          double strike,
                          int32_t earliest,
                          int32_t expiry,
                          int32_t american,
                          uint64_t settings,
                          uint64_t *out,
                          struct ItofinError *error);

/**
 * Engine kind: 0 analytic European (BSM process), 1 analytic Heston (model), 2 MC engine.
 */
int32_t itofin_option_set_engine(struct Context *ctx,
                                 uint64_t option,
                                 uint64_t source,
                                 int32_t kind,
                                 size_t integration_order,
                                 struct ItofinError *error);

/**
 * Field: 0 NPV, 1 delta, 2 gamma, 3 theta, 4 vega, 5 rho, 6 dividend rho,
 * 7 error estimate, 8 exercise probability. Missing fields return core errors.
 */
int32_t itofin_option_value(struct Context *ctx,
                            uint64_t option,
                            int32_t field,
                            double *out,
                            struct ItofinError *error);

/**
 * Calculate if requested, then report cache validity.
 */
int32_t itofin_option_calculate(struct Context *ctx,
                                uint64_t option,
                                int32_t calculate,
                                int32_t *out,
                                struct ItofinError *error);

int32_t itofin_option_results(struct Context *ctx,
                              uint64_t option,
                              uint64_t *out,
                              struct ItofinError *error);

int32_t itofin_heston_process_new(struct Context *ctx,
                                  struct HestonProcessConfig config,
                                  uint64_t *out,
                                  struct ItofinError *error);

int32_t itofin_heston_model_new(struct Context *ctx,
                                uint64_t process,
                                uint64_t *out,
                                struct ItofinError *error);

int32_t itofin_hullwhite_new(struct Context *ctx,
                             uint64_t curve,
                             double a,
                             double sigma,
                             uint64_t *out,
                             struct ItofinError *error);

/**
 * Kind 0 Heston process, 1 Heston model, 2 HullWhite.
 * Heston fields: v0, kappa, theta, sigma, rho. HullWhite fields: a, sigma, r0.
 */
int32_t itofin_model_parameter(struct Context *ctx,
                               uint64_t handle,
                               int32_t kind,
                               size_t field,
                               double *out,
                               struct ItofinError *error);

int32_t itofin_hullwhite_bond_option(struct Context *ctx,
                                     uint64_t model,
                                     int32_t kind,
                                     double strike,
                                     double maturity,
                                     double bond_maturity,
                                     double *out,
                                     struct ItofinError *error);

int32_t itofin_levenberg_marquardt_new(struct Context *ctx,
                                       double epsfcn,
                                       double xtol,
                                       double gtol,
                                       int32_t jacobian,
                                       uint64_t *out,
                                       struct ItofinError *error);

int32_t itofin_end_criteria_new(struct Context *ctx,
                                struct EndCriteriaConfig config,
                                uint64_t *out,
                                struct ItofinError *error);

int32_t itofin_heston_helper_new(struct Context *ctx,
                                 struct HestonHelperConfig cfg,
                                 uint64_t *out,
                                 struct ItofinError *error);

int32_t itofin_swaption_helper_new(struct Context *ctx,
                                   struct SwaptionHelperConfig cfg,
                                   uint64_t *out,
                                   struct ItofinError *error);

/**
 * Kind 0 Heston helper, 1 swaption helper.
 */
int32_t itofin_helper_error(struct Context *ctx,
                            uint64_t helper,
                            int32_t kind,
                            double *out,
                            struct ItofinError *error);

/**
 * Calibration kind 0 Heston (integration order), 1 HullWhite (fix_reversion).
 */
int32_t itofin_model_calibrate(struct Context *ctx,
                               uint64_t model,
                               int32_t kind,
                               const uint64_t *helpers,
                               size_t helpers_len,
                               uint64_t method,
                               uint64_t criteria,
                               size_t integration_order,
                               int32_t fix_reversion,
                               struct ItofinError *error);

/**
 * Kind 0 European BSM, 1 European Heston, 2 American BSM.
 */
int32_t itofin_mc_engine_new(struct Context *ctx,
                             uint64_t process,
                             int32_t kind,
                             struct McConfig cfg,
                             uint64_t *out,
                             struct ItofinError *error);

int32_t itofin_flat_hazard_new(struct Context *ctx,
                               const struct ItofinFlatHazardConfig *config,
                               uint64_t *out,
                               struct ItofinError *error);

int32_t itofin_interpolated_hazard_new(struct Context *ctx,
                                       const int32_t *dates,
                                       const double *rates,
                                       size_t count,
                                       uint64_t dc,
                                       uint64_t *out,
                                       struct ItofinError *error);

int32_t itofin_piecewise_default_new(struct Context *ctx,
                                     int32_t reference,
                                     const uint64_t *helpers,
                                     size_t count,
                                     uint64_t dc,
                                     uint64_t *out,
                                     struct ItofinError *error);

/**
 * kind: 0 survival, 1 default probability, 2 density, 3 hazard. use_date: 0 time, 1 date.
 */
int32_t itofin_default_curve_value(struct Context *ctx,
                                   uint64_t id,
                                   int32_t kind,
                                   double t,
                                   int32_t serial,
                                   int32_t use_date,
                                   int32_t extrapolate,
                                   double *out,
                                   struct ItofinError *error);

/**
 * capacity zero queries the required length. Node reads run the lazy bootstrap.
 */
int32_t itofin_default_curve_nodes(struct Context *ctx,
                                   uint64_t id,
                                   struct ItofinCreditNode *out,
                                   size_t capacity,
                                   size_t *count,
                                   struct ItofinError *error);

int32_t itofin_default_curve_calculate(struct Context *ctx, uint64_t id, struct ItofinError *error);

int32_t itofin_spread_cds_helper_new(struct Context *ctx,
                                     const struct ItofinSpreadCdsConfig *config,
                                     uint64_t *out,
                                     struct ItofinError *error);

int32_t itofin_default_helper_dates(struct Context *ctx,
                                    uint64_t id,
                                    int32_t *pillar,
                                    int32_t *latest,
                                    struct ItofinError *error);

int32_t itofin_cds_engine_new(struct Context *ctx,
                              const struct ItofinCdsEngineConfig *config,
                              uint64_t *out,
                              struct ItofinError *error);

int32_t itofin_cds_new(struct Context *ctx,
                       const struct ItofinCdsConfig *config,
                       uint64_t *out,
                       struct ItofinError *error);

int32_t itofin_make_cds(struct Context *ctx,
                        const struct ItofinMakeCdsConfig *config,
                        uint64_t *out,
                        struct ItofinError *error);

int32_t itofin_cds_set_engine(struct Context *ctx,
                              uint64_t id,
                              uint64_t engine,
                              struct ItofinError *error);

/**
 * query: 0 NPV, 1 fair spread, 2 fair upfront, 3 notional, 4 coupon NPV,
 * 5 default NPV, 6 calculate, 7 is-calculated.
 */
int32_t itofin_cds_value(struct Context *ctx,
                         uint64_t id,
                         int32_t query,
                         double *out,
                         struct ItofinError *error);

int32_t itofin_cds_rebate(struct Context *ctx,
                          uint64_t id,
                          int32_t *has,
                          double *amount,
                          int32_t *serial,
                          struct ItofinError *error);

int32_t itofin_cds_implied_hazard(struct Context *ctx,
                                  uint64_t id,
                                  double target,
                                  uint64_t discount,
                                  uint64_t dc,
                                  double recovery,
                                  double accuracy,
                                  int32_t model,
                                  double *out,
                                  struct ItofinError *error);

int32_t itofin_cds_results(struct Context *ctx,
                           uint64_t id,
                           uint64_t *out,
                           struct ItofinError *error);

int32_t itofin_deposit_helper_new(struct Context *ctx,
                                  uint64_t quote_id,
                                  double rate,
                                  bool from_rate,
                                  uint64_t index,
                                  uint64_t *out,
                                  struct ItofinError *error);

int32_t itofin_swap_helper_new(struct Context *ctx,
                               const struct ItofinSwapHelperConfig *cfg,
                               uint64_t *out,
                               struct ItofinError *error);

/**
 * Mode 0 quote+period, 1 fixed rate+period, 2 months, 3 explicit dates.
 */
int32_t itofin_fra_helper_new(struct Context *ctx,
                              int32_t mode,
                              const struct ItofinFraHelperConfig *cfg,
                              uint64_t *out,
                              struct ItofinError *error);

/**
 * Mode 0 tenor months, 1 explicit/optional end date, 2 index conventions.
 */
int32_t itofin_futures_helper_new(struct Context *ctx,
                                  int32_t mode,
                                  const struct ItofinFuturesHelperConfig *cfg,
                                  uint64_t *out,
                                  struct ItofinError *error);

int32_t itofin_ois_helper_new(struct Context *ctx,
                              const struct ItofinOisHelperConfig *cfg,
                              uint64_t *out,
                              struct ItofinError *error);

int32_t itofin_bond_helper_new(struct Context *ctx,
                               const struct ItofinBondHelperConfig *cfg,
                               const double *coupons,
                               size_t len,
                               uint64_t *out,
                               struct ItofinError *error);

/**
 * Query 0 implied quote, 1 quote error, 2 market quote, 3 futures convexity adjustment.
 */
int32_t itofin_helper_value(struct Context *ctx,
                            uint64_t id,
                            int32_t query,
                            double *out,
                            struct ItofinError *error);

/**
 * Query 0 maturity, 1 pillar, 2 earliest, 3 latest, 4 latest relevant date.
 */
int32_t itofin_helper_date(struct Context *ctx,
                           uint64_t id,
                           int32_t query,
                           int32_t *out,
                           struct ItofinError *error);

int32_t itofin_swaption_vol_matrix_new(struct Context *ctx,
                                       const struct ItofinVolGridConfig *cfg,
                                       uint64_t *out,
                                       struct ItofinError *error);

int32_t itofin_capfloor_vol_surface_new(struct Context *ctx,
                                        const struct ItofinVolGridConfig *cfg,
                                        uint64_t *out,
                                        struct ItofinError *error);

/**
 * Query 0 tenor, 1 date, 2 time.
 */
int32_t itofin_capfloor_vol_query(struct Context *ctx,
                                  uint64_t id,
                                  int32_t kind,
                                  int32_t length,
                                  int32_t unit,
                                  int32_t serial,
                                  double time,
                                  double strike,
                                  int32_t extrapolate,
                                  double *out,
                                  struct ItofinError *error);

int32_t itofin_vanilla_swap_new(struct Context *ctx,
                                struct ItofinVanillaSwapConfig a,
                                uint64_t *out,
                                struct ItofinError *error);

int32_t itofin_make_vanilla_swap(struct Context *ctx,
                                 struct ItofinMakeSwapConfig a,
                                 uint64_t *out,
                                 struct ItofinError *error);

int32_t itofin_make_ois(struct Context *ctx,
                        struct ItofinMakeSwapConfig a,
                        uint64_t *out,
                        struct ItofinError *error);

int32_t itofin_vanilla_swap_set_engine(struct Context *ctx,
                                       uint64_t id,
                                       uint64_t discount,
                                       uint64_t settings_id,
                                       struct ItofinError *error);

/**
 * Swap kind: 0 vanilla, 1 OIS. Field: 0 NPV, 1 fair rate, 2 nominal,
 * 3 fixed rate, 4 calculated flag (does not calculate), 5 calculate.
 */
int32_t itofin_swap_value(struct Context *ctx,
                          uint64_t id,
                          int32_t kind,
                          int32_t field,
                          Real *out,
                          struct ItofinError *error);

int32_t itofin_swap_results(struct Context *ctx,
                            uint64_t id,
                            int32_t kind,
                            uint64_t *out,
                            struct ItofinError *error);

int32_t itofin_fra_new(struct Context *ctx,
                       struct ItofinFraConfig a,
                       uint64_t *out,
                       struct ItofinError *error);

/**
 * Field 0 NPV, 1 forward rate, 2 amount.
 */
int32_t itofin_fra_value(struct Context *ctx,
                         uint64_t id,
                         int32_t field,
                         Real *out,
                         struct ItofinError *error);

/**
 * Field 0 value date, 1 adjusted maturity date.
 */
int32_t itofin_fra_date(struct Context *ctx,
                        uint64_t id,
                        int32_t field,
                        int32_t *out,
                        struct ItofinError *error);

int32_t itofin_optionlet_stripper_new(struct Context *ctx,
                                      uint64_t surface,
                                      uint64_t index,
                                      int32_t kind,
                                      double accuracy,
                                      uint32_t max_iter,
                                      double displacement,
                                      uint64_t discount,
                                      int32_t frequency_length,
                                      int32_t frequency_unit,
                                      int32_t has_frequency,
                                      uint64_t *out,
                                      struct ItofinError *error);

int32_t itofin_optionlet_stripper_switch_strike(struct Context *ctx,
                                                uint64_t id,
                                                double *out,
                                                struct ItofinError *error);

/**
 * Pass null output/capacity zero to size the caller-owned rates buffer.
 */
int32_t itofin_optionlet_stripper_rates(struct Context *ctx,
                                        uint64_t id,
                                        double *out,
                                        size_t capacity,
                                        size_t *written,
                                        struct ItofinError *error);

int32_t itofin_stripped_optionlet_adapter_new(struct Context *ctx,
                                              uint64_t stripper,
                                              uint64_t setting,
                                              uint64_t *out,
                                              struct ItofinError *error);

#endif  /* ITOFIN_H */
