# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from itofin import quotes
from itofin import termstructures
from itofin import time
import typing
__all__ = [
    "BatesProcess",
    "BlackScholesProcess",
    "HestonProcess",
    "Merton76Process",
]

@typing.final
class BatesProcess:
    r"""
    Heston variance with independent constant-intensity lognormal jumps.

    Retains live spot and yield curves for analytic pricing, not path generation.
    """
    def __init__(self, spot: quotes.SimpleQuote, risk_free: termstructures.YieldTermStructure, dividend: termstructures.YieldTermStructure, v0: builtins.float, kappa: builtins.float, theta: builtins.float, sigma: builtins.float, rho: builtins.float, lambda_: builtins.float, nu: builtins.float, delta: builtins.float) -> None:
        r"""
        Retain the market and validate eight finite Bates parameters.

        Variance, mean reversion and variance volatility must be positive;
        correlation is in [-1, 1], and lambda_ and delta are nonnegative.
        """
    def v0(self) -> builtins.float:
        r"""
        Return the initial variance.
        """
    def kappa(self) -> builtins.float:
        r"""
        Return the variance mean-reversion speed.
        """
    def theta(self) -> builtins.float:
        r"""
        Return the long-run variance.
        """
    def sigma(self) -> builtins.float:
        r"""
        Return the volatility of variance.
        """
    def rho(self) -> builtins.float:
        r"""
        Return the spot/variance correlation.
        """
    def lambda_(self) -> builtins.float:
        r"""
        Return the Poisson jump intensity.
        """
    def nu(self) -> builtins.float:
        r"""
        Return the logarithmic jump mean.
        """
    def delta(self) -> builtins.float:
        r"""
        Return the logarithmic jump standard deviation.
        """
    def spot(self) -> builtins.float:
        r"""
        Return the current retained spot quote.
        """
    def initial_values(self) -> builtins.list[builtins.float]:
        r"""
        Return the current spot and initial variance.
        """
    def time(self, date: time.Date) -> builtins.float:
        r"""
        Convert a date using the risk-free curve's clock.
        """

@typing.final
class BlackScholesProcess:
    r"""
    A generalized Black-Scholes process, built from scalars or curve objects.

    The Handle plumbing is assembled internally, so no handle crosses the
    binding boundary. The constructor takes the conventional
    (risk_free_rate, dividend_yield) order and places the two curves in the
    core's own order at a single call site.
    """
    def __init__(self, spot: builtins.float, risk_free_rate: builtins.float, dividend_yield: builtins.float, volatility: builtins.float, reference_date: time.Date, day_counter: time.DayCounter) -> None:
        r"""
        Build a flat-market process from scalar inputs.

        Args:
            spot (float): The spot level, held as a quote.
            risk_free_rate (float): The flat risk-free rate, made into a curve
                compounded continuously on an annual frequency.
            dividend_yield (float): The flat dividend yield, made into a curve on the
                same convention as the risk-free rate.
            volatility (float): The flat Black volatility.
            reference_date (Date): The date the three flat curves are anchored on.
            day_counter (DayCounter): The day count the curves accrue on.
        """
    @staticmethod
    def from_curves(spot: builtins.float, risk_free: termstructures.YieldTermStructure, dividend: termstructures.YieldTermStructure, vol: termstructures.BlackVolTermStructure) -> BlackScholesProcess:
        r"""
        Build a process from term-structure objects instead of scalars.

        The three legs are bound by name and placed in the core's order at a
        single call site, the same risk-free/dividend argument-order footgun the
        scalar constructor guards against.

        Args:
            spot (float): The spot level, held as a quote.
            risk_free (YieldTermStructure): The risk-free discount curve.
            dividend (YieldTermStructure): The dividend curve.
            vol (BlackVolTermStructure): The Black volatility surface.

        Returns:
            BlackScholesProcess: A process over the three supplied term structures.
        """
    def risk_free_rate(self) -> builtins.float:
        r"""
        Return the risk-free rate carried by the process.

        Returns:
            float: The continuously compounded zero rate on the risk-free curve at the
            reference date.
        """
    def dividend_yield(self) -> builtins.float:
        r"""
        Return the dividend yield carried by the process.

        Returns:
            float: The continuously compounded zero rate on the dividend curve at the
            reference date.
        """

@typing.final
class HestonProcess:
    r"""
    The square-root stochastic-variance process.

    The two flat yield curves and the spot quote are assembled behind their
    handles internally, so no handle crosses the binding boundary.
    """
    def __init__(self, risk_free_rate: builtins.float, dividend_yield: builtins.float, spot: builtins.float, v0: builtins.float, kappa: builtins.float, theta: builtins.float, sigma: builtins.float, rho: builtins.float, reference_date: time.Date, day_counter: time.DayCounter) -> None:
        r"""
        Build the process from scalar market inputs and the five parameters.

        Args:
            risk_free_rate (float): The flat risk-free rate, made into a curve
                compounded continuously on an annual frequency.
            dividend_yield (float): The flat dividend yield, made into a curve on the
                same convention as the risk-free rate.
            spot (float): The spot level, held as a quote.
            v0 (float): The initial variance.
            kappa (float): The mean-reversion speed.
            theta (float): The long-run variance.
            sigma (float): The volatility of variance.
            rho (float): The spot/variance correlation.
            reference_date (Date): The date the two flat curves are anchored on.
            day_counter (DayCounter): The day count the curves accrue on.
        """
    def v0(self) -> builtins.float:
        r"""
        Return the initial variance.

        Returns:
            float: The initial variance v0.
        """
    def kappa(self) -> builtins.float:
        r"""
        Return the mean-reversion speed.

        Returns:
            float: The mean-reversion speed kappa.
        """
    def theta(self) -> builtins.float:
        r"""
        Return the long-run variance.

        Returns:
            float: The long-run variance theta.
        """
    def sigma(self) -> builtins.float:
        r"""
        Return the volatility of variance.

        Returns:
            float: The volatility of variance sigma.
        """
    def rho(self) -> builtins.float:
        r"""
        Return the spot/variance correlation.

        Returns:
            float: The spot/variance correlation rho.
        """

@typing.final
class Merton76Process:
    r"""
    Merton's lognormal-jump model retaining observable market and jump inputs.

    This process supports European pricing. Generic drift, diffusion and path
    generation are unavailable because a Gaussian step cannot represent jumps.
    """
    def __init__(self, spot: quotes.SimpleQuote, risk_free: termstructures.YieldTermStructure, dividend: termstructures.YieldTermStructure, volatility: termstructures.BlackVolTermStructure, jump_intensity: quotes.SimpleQuote, log_mean_jump: quotes.SimpleQuote, log_jump_volatility: quotes.SimpleQuote) -> None:
        r"""
        Retain the diffusion market and the three live lognormal-jump quotes.

        Jump intensity and log-jump volatility must be finite and nonnegative;
        the log-jump mean must be finite. Invalid inputs raise ItofinError.
        """
    def spot(self) -> builtins.float:
        r"""
        Return the current spot held by the diffusion market.
        """
    def jump_intensity(self) -> builtins.float:
        r"""
        Return the current jump intensity.
        """
    def log_mean_jump(self) -> builtins.float:
        r"""
        Return the current mean of the logarithmic jump size.
        """
    def log_jump_volatility(self) -> builtins.float:
        r"""
        Return the current standard deviation of the logarithmic jump size.
        """
    def time(self, date: time.Date) -> builtins.float:
        r"""
        Convert a date with the risk-free curve's reference date and day count.
        """
