# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "BusinessDayConvention",
    "Calendar",
    "Date",
    "DateGeneration",
    "DayCounter",
    "Frequency",
    "Period",
    "Schedule",
    "is_imm_date",
    "next_imm_date",
]

@typing.final
class Calendar:
    r"""
    A business-day calendar.
    """
    @staticmethod
    def target() -> Calendar:
        r"""
        The TARGET calendar.

        Returns:
            Calendar: The TARGET business-day calendar.
        """
    @staticmethod
    def null_calendar() -> Calendar:
        r"""
        The calendar holding no holidays at all.

        Returns:
            Calendar: The null calendar, on which every day is a business day.
        """
    @staticmethod
    def weekends_only() -> Calendar:
        r"""
        The weekends-only calendar: Saturdays and Sundays are holidays and no
        other day is. The calendar the ISDA CDS conventions roll on.

        It is not substitutable by the null calendar, which holds no holidays at
        all, nor by a national calendar, which adds public holidays.

        Returns:
            Calendar: The weekends-only calendar.
        """
    @staticmethod
    def united_kingdom() -> Calendar:
        r"""
        The UK settlement calendar. Only the Settlement market is exposed:
        the Exchange and Metals markets share an identical business-day rule in
        the core and differ solely in their name.

        Returns:
            Calendar: The UK settlement calendar.
        """
    def adjust(self, date: Date, convention: BusinessDayConvention) -> Date:
        r"""
        Roll a date to the nearest business day.

        Args:
            date (Date): The date to roll.
            convention (BusinessDayConvention): The rolling rule to apply.

        Returns:
            Date: The adjusted date, unchanged when it is already a business day.
        """
    def advance(self, date: Date, n: builtins.int, unit: builtins.str, convention: BusinessDayConvention, end_of_month: builtins.bool) -> Date:
        r"""
        Advance a date by n units and adjust the result.

        Args:
            date (Date): The date to advance from.
            n (int): The number of units to advance, which may be negative.
            unit (str): One of "Days", "Weeks", "Months", "Years".
            convention (BusinessDayConvention): The rule the advanced date is rolled under.
            end_of_month (bool): Keep the result on the month end when the starting
                date is one.

        Returns:
            Date: The advanced and adjusted date.

        Raises:
            ItofinError: If unit is not one of the four accepted strings.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the calendar and its name.

        Returns:
            str: The calendar as Calendar(name).
        """

@typing.final
class Date:
    r"""
    A calendar date with a validation guard.

    Every constructor and every arithmetic result is range-checked before the
    core is reached, so an out-of-range date is an error rather than a panic.
    """
    @property
    def year(self) -> builtins.int:
        r"""
        The year.
        """
    @property
    def month(self) -> builtins.int:
        r"""
        The month, from 1 to 12.
        """
    @property
    def day(self) -> builtins.int:
        r"""
        The day of the month.
        """
    def __init__(self, day: builtins.int, month: builtins.int, year: builtins.int) -> None:
        r"""
        Build a date from its three components.

        Args:
            day (int): The day of the month, within the length of that month.
            month (int): The month, from 1 to 12.
            year (int): The year, from 1901 to 2199.

        Raises:
            ItofinError: If month is outside [1, 12], year is outside
                [1901, 2199], or day is outside the length of that month.
        """
    def __add__(self, days: builtins.int) -> Date:
        r"""
        Shift the date forward by a number of calendar days.

        Args:
            days (int): The number of calendar days to add.

        Returns:
            Date: The shifted date.

        Raises:
            ItofinError: If the result falls outside the representable date
                range.
        """
    def __sub__(self, other: typing.Any) -> typing.Any:
        r"""
        The signed number of days from other to this date.

        The other operand may also be an int, which shifts the date back by that
        many calendar days and returns a Date. Anything else raises TypeError.

        Args:
            other (Date): The date to measure from.

        Returns:
            int: The signed day count between the two dates.
        """
    def __eq__(self, other: Date) -> builtins.bool:
        r"""
        Whether the two dates are the same calendar day.

        Args:
            other (object): The date to compare against.

        Returns:
            bool: True when both stand for the same day.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the calendar day, the field equality compares.

        Returns:
            int: The hash of the date, so equal dates hash equal.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the constructor form of the date.

        Returns:
            str: The date as Date(day, month, year).
        """

@typing.final
class DayCounter:
    r"""
    A year-fraction convention.
    """
    @staticmethod
    def actual360() -> DayCounter:
        r"""
        The Actual/360 convention.

        Returns:
            DayCounter: An Actual/360 day counter.
        """
    @staticmethod
    def actual365_fixed() -> DayCounter:
        r"""
        The Actual/365 (Fixed) convention.

        Returns:
            DayCounter: An Actual/365 (Fixed) day counter.
        """
    @staticmethod
    def actual_actual_isda() -> DayCounter:
        r"""
        The Actual/Actual (ISDA) convention.

        Returns:
            DayCounter: An Actual/Actual day counter on the ISDA convention.
        """
    @staticmethod
    def thirty360_bond_basis() -> DayCounter:
        r"""
        The 30/360 (Bond Basis) convention.

        Returns:
            DayCounter: A 30/360 day counter on the bond-basis convention.
        """
    def year_fraction(self, d1: Date, d2: Date) -> builtins.float:
        r"""
        The period [d1, d2] as a fraction of a year under this convention.

        Args:
            d1 (Date): The start of the period.
            d2 (Date): The end of the period.

        Returns:
            float: The year fraction between the two dates.
        """
    def __eq__(self, other: DayCounter) -> builtins.bool:
        r"""
        Equality by convention name, so two independently built Actual360s
        are equal.

        Args:
            other (object): The day counter to compare against.

        Returns:
            bool: True when both carry the same convention name.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the convention name, the field equality compares.

        Returns:
            int: The hash of the convention name, so equal day counters hash equal.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the day counter and its convention name.

        Returns:
            str: The day counter as DayCounter(name).
        """

@typing.final
class Period:
    r"""
    A signed length in one calendar unit (unit: Days, Weeks, Months, Years).
    """
    def __init__(self, n: builtins.int, unit: builtins.str) -> None:
        r"""
        Build a period of n units.

        Args:
            n (int): The length, which may be negative.
            unit (str): One of "Days", "Weeks", "Months", "Years".

        Raises:
            ItofinError: If unit is not one of the four accepted strings.
        """
    def __eq__(self, other: Period) -> builtins.bool:
        r"""
        Semantic equality: 7 Days equals 1 Week and 12 Months equals 1 Year,
        while an undecidable pair such as 30 Days against 1 Month is not equal.

        Args:
            other (object): The period to compare against.

        Returns:
            bool: True when the two lengths are decidably the same.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the canonical form, so equal periods hash equal.

        Normalizing collapses 7 Days onto 1 Week, 12 Months onto 1 Year and
        every zero length onto 0 Days before the hash is taken.

        Returns:
            int: The hash of the normalized length and unit.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the constructor form of the period.

        Returns:
            str: The period as Period(length, unit).
        """

@typing.final
class Schedule:
    r"""
    A sequence of coupon dates built through MakeSchedule.

    termination_convention rolls the last date only, and defaults to
    convention. CDS conventions need the two to differ: a credit helper leaves
    its maturity unadjusted while paying Following.
    """
    def __init__(self, start: Date, end: Date, frequency: Frequency, calendar: Calendar, convention: BusinessDayConvention, rule: DateGeneration = DateGeneration.Forward, termination_convention: typing.Optional[BusinessDayConvention] = None) -> None:
        r"""
        Build the schedule.

        Args:
            start (Date): The effective date, which must be strictly before end.
            end (Date): The termination date.
            frequency (Frequency): The coupon frequency the interior dates are spaced at.
            calendar (Calendar): The calendar the dates roll on.
            convention (BusinessDayConvention): The rule every date but the last is rolled under.
            rule (DateGeneration): The date-generation rule; defaults to Forward.
            termination_convention (BusinessDayConvention | None): The rule the last date is rolled under;
                None applies convention to it as well.

        Raises:
            ItofinError: If start is not strictly before end.
        """
    def size(self) -> builtins.int:
        r"""
        The number of dates in the schedule.

        Returns:
            int: The date count, one more than the number of periods.
        """
    def date(self, i: builtins.int) -> Date:
        r"""
        The i-th date in the schedule.

        Args:
            i (int): The zero-based index into the dates.

        Returns:
            Date: The date at that index.

        Raises:
            ItofinError: If i is out of range.
        """
    def dates(self) -> builtins.list[Date]:
        r"""
        All the schedule dates.

        Returns:
            list[Date]: The dates in order, from the effective date to the termination date.
        """

@typing.final
class BusinessDayConvention(enum.Enum):
    r"""
    A holiday-rolling rule. Every core variant is covered; the four listed
    last are appended, so the integer values of the first three are unchanged.
    """
    ModifiedFollowing = ...
    Following = ...
    Unadjusted = ...
    Preceding = ...
    ModifiedPreceding = ...
    HalfMonthModifiedFollowing = ...
    Nearest = ...

@typing.final
class DateGeneration(enum.Enum):
    r"""
    The rule a Schedule generates its dates by.

    Backward and Forward roll from one end of the range to the other; Zero keeps
    only the two endpoints; the ThirdWednesday and Twentieth families snap the
    interior dates onto an IMM Wednesday or the twentieth of the month. A
    Schedule builds under the three CDS rules, but SpreadCdsHelper rejects them:
    their maturity comes from a core routine that is not ported yet.
    """
    Backward = ...
    Forward = ...
    Zero = ...
    ThirdWednesday = ...
    ThirdWednesdayInclusive = ...
    Twentieth = ...
    TwentiethIMM = ...
    OldCDS = ...
    CDS = ...
    CDS2015 = ...

@typing.final
class Frequency(enum.Enum):
    r"""
    A coupon or fixing frequency.

    Only the variants the ported fixtures use are surfaced; new ones are
    appended, so the integer values of the existing variants are unchanged.
    """
    Annual = ...
    Semiannual = ...
    Quarterly = ...
    Monthly = ...

def is_imm_date(date: Date, main_cycle: builtins.bool = False) -> builtins.bool:
    r"""
    Whether date is an IMM date.

    An IMM date is the third Wednesday of the month, and of March, June,
    September or December only when main_cycle is set.

    Args:
        date (Date): The date to test.
        main_cycle (bool): Restrict the test to the March/June/September/December
            cycle.

    Returns:
        bool: True when date is an IMM date under the selected cycle.
    """

def next_imm_date(date: Date, main_cycle: builtins.bool = False) -> Date:
    r"""
    The next IMM date strictly following date.

    Args:
        date (Date): The date to start from; the result is strictly after it.
        main_cycle (bool): Restrict the result to the March/June/September/December
            cycle.

    Returns:
        Date: The next IMM date under the selected cycle.
    """
