//! Sobol low-discrepancy sequence generator, ported from
//! `ql/math/randomnumbers/sobolrsg.{hpp,cpp}`.
//!
//! A Gray code counter and bitwise operations are used for very fast
//! sequence generation. The implementation relies on primitive polynomials
//! modulo two and direction-integer initializers from Peter Jaeckel's
//! "Monte Carlo Methods in Finance" plus the Sobol-Levitan, Lemieux, Joe-Kuo
//! and Kuo tables shipped with QuantLib (see `tables/`, generated by
//! `scripts/gen_sobol_tables.py`).

mod mt;
mod tables;

/// Number of primitive polynomials modulo two shipped with the library,
/// i.e. the maximum supported dimensionality.
pub const PPMT_MAX_DIM: usize = tables::PPMT_MAX_DIM;

/// Choice of free direction integers for dimensions 2 and above.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DirectionIntegers {
    Unit,
    Jaeckel,
    SobolLevitan,
    SobolLevitanLemieux,
    JoeKuoD5,
    JoeKuoD6,
    JoeKuoD7,
    Kuo,
    Kuo2,
    Kuo3,
}

struct InitializerTable {
    offsets: &'static [u32],
    parts: &'static [&'static [u32]],
}

impl InitializerTable {
    fn tabulated_dimensions(&self) -> usize {
        self.offsets.len() - 1
    }

    fn entry(&self, k: usize) -> &'static [u32] {
        let mut start = self.offsets[k] as usize;
        let len = (self.offsets[k + 1] - self.offsets[k]) as usize;
        for part in self.parts {
            if start < part.len() {
                return &part[start..start + len];
            }
            start -= part.len();
        }
        unreachable!("initializer table offsets exceed the table data length")
    }
}

fn initializer_table(direction_integers: DirectionIntegers) -> Option<InitializerTable> {
    let (offsets, parts) = match direction_integers {
        DirectionIntegers::Unit => return None,
        DirectionIntegers::Jaeckel => (tables::JAECKEL_OFFSETS, tables::JAECKEL_PARTS),
        DirectionIntegers::SobolLevitan => {
            (tables::SOBOL_LEVITAN_OFFSETS, tables::SOBOL_LEVITAN_PARTS)
        }
        DirectionIntegers::SobolLevitanLemieux => (tables::LEMIEUX_OFFSETS, tables::LEMIEUX_PARTS),
        DirectionIntegers::JoeKuoD5 => (tables::JOE_KUO_D5_OFFSETS, tables::JOE_KUO_D5_PARTS),
        DirectionIntegers::JoeKuoD6 => (tables::JOE_KUO_D6_OFFSETS, tables::JOE_KUO_D6_PARTS),
        DirectionIntegers::JoeKuoD7 => (tables::JOE_KUO_D7_OFFSETS, tables::JOE_KUO_D7_PARTS),
        DirectionIntegers::Kuo => (tables::KUO_OFFSETS, tables::KUO_PARTS),
        DirectionIntegers::Kuo2 => (tables::KUO2_OFFSETS, tables::KUO2_PARTS),
        DirectionIntegers::Kuo3 => (tables::KUO3_OFFSETS, tables::KUO3_PARTS),
    };
    Some(InitializerTable { offsets, parts })
}

fn next_polynomial(table: &[&'static [u32]], current_degree: &mut usize, index: &mut usize) -> u32 {
    if *index >= table[*current_degree - 1].len() {
        *current_degree += 1;
        *index = 0;
    }
    let polynomial = table[*current_degree - 1][*index];
    *index += 1;
    polynomial
}

/// Sobol low-discrepancy sequence generator.
pub struct SobolRsg {
    dimensionality: usize,
    sequence_counter: u32,
    first_draw: bool,
    sequence: Vec<f64>,
    integer_sequence: Vec<u32>,
    direction_integers: Vec<Vec<u32>>,
    use_gray_code: bool,
}

impl SobolRsg {
    /// Creates a generator using the Gray code counter, like QuantLib's
    /// default constructor arguments.
    ///
    /// Unlike QuantLib, a zero seed is used literally instead of drawing a
    /// clock-based seed; the seed only matters for dimensions beyond the
    /// tabulated initializers, where free direction integers are drawn from
    /// a seeded Mersenne twister.
    ///
    /// # Panics
    ///
    /// Panics if `dimensionality` is zero or exceeds [`PPMT_MAX_DIM`].
    pub fn new(dimensionality: usize, seed: u64, direction_integers: DirectionIntegers) -> Self {
        Self::with_gray_code(dimensionality, seed, direction_integers, true)
    }

    /// Creates a generator choosing the generating integer: the Gray code
    /// `G(n)` when `use_gray_code` is true, plain `n` otherwise.
    pub fn with_gray_code(
        dimensionality: usize,
        seed: u64,
        direction_integers: DirectionIntegers,
        use_gray_code: bool,
    ) -> Self {
        assert!(dimensionality > 0, "dimensionality must be greater than 0");
        assert!(
            dimensionality <= tables::PPMT_MAX_DIM,
            "dimensionality {dimensionality} exceeds the number of available primitive polynomials modulo two ({})",
            tables::PPMT_MAX_DIM
        );

        let mut degree = vec![0usize; dimensionality];
        let mut ppmt = vec![0u32; dimensionality];
        let use_alt_polynomials = matches!(
            direction_integers,
            DirectionIntegers::Kuo
                | DirectionIntegers::Kuo2
                | DirectionIntegers::Kuo3
                | DirectionIntegers::SobolLevitan
                | DirectionIntegers::SobolLevitanLemieux
        );
        let alt_limit = if use_alt_polynomials {
            tables::MAX_ALT_POLYNOMIALS
        } else {
            0
        };

        let mut current_degree = 1usize;
        let mut index = 0usize;
        let mut k = 1;
        while k < dimensionality.min(alt_limit) {
            ppmt[k] = next_polynomial(
                &tables::ALT_PRIMITIVE_POLYNOMIALS,
                &mut current_degree,
                &mut index,
            );
            degree[k] = current_degree;
            k += 1;
        }
        while k < dimensionality {
            ppmt[k] = next_polynomial(
                &tables::PRIMITIVE_POLYNOMIALS,
                &mut current_degree,
                &mut index,
            );
            degree[k] = current_degree;
            k += 1;
        }

        let mut directions = vec![vec![0u32; dimensionality]; 32];
        for (j, row) in directions.iter_mut().enumerate() {
            row[0] = 1u32 << (31 - j);
        }

        let max_tabulated = match initializer_table(direction_integers) {
            None => {
                for k in 1..dimensionality {
                    for l in 1..=degree[k] {
                        directions[l - 1][k] = 1u32 << (32 - l);
                    }
                }
                dimensionality
            }
            Some(table) => {
                let max_tabulated = table.tabulated_dimensions() + 1;
                #[allow(clippy::needless_range_loop)]
                for k in 1..dimensionality.min(max_tabulated) {
                    for (j, &coefficient) in table.entry(k - 1).iter().enumerate() {
                        directions[j][k] = coefficient << (32 - j - 1);
                    }
                }
                max_tabulated
            }
        };

        if dimensionality > max_tabulated {
            let mut rng = mt::MersenneTwister::new(seed);
            for k in max_tabulated..dimensionality {
                for l in 1..=degree[k] {
                    loop {
                        let u = rng.next_real();
                        let drawn = (u * f64::from(1u32 << l)) as u32;
                        if drawn & 1 != 0 {
                            directions[l - 1][k] = drawn << (32 - l);
                            break;
                        }
                    }
                }
            }
        }

        for k in 1..dimensionality {
            let gk = degree[k];
            for l in gk..32 {
                let mut n = directions[l - gk][k] >> gk;
                for j in 1..gk {
                    if (ppmt[k] >> (gk - j - 1)) & 1 != 0 {
                        n ^= directions[l - j][k];
                    }
                }
                n ^= directions[l - gk][k];
                directions[l][k] = n;
            }
        }

        let mut integer_sequence = vec![0u32; dimensionality];
        if use_gray_code {
            integer_sequence.copy_from_slice(&directions[0]);
        }

        Self {
            dimensionality,
            sequence_counter: 0,
            first_draw: true,
            sequence: vec![0.0; dimensionality],
            integer_sequence,
            direction_integers: directions,
            use_gray_code,
        }
    }

    /// Skips to the n-th sample in the low-discrepancy sequence and returns it.
    pub fn skip_to(&mut self, skip: u32) -> &[u32] {
        let n = skip
            .checked_add(1)
            .expect("skip exceeds the Sobol sequence period");

        if self.use_gray_code {
            let ops = (f64::from(n).ln() / std::f64::consts::LN_2) as u32 + 1;
            let gray = n ^ (n >> 1);
            for (k, value) in self.integer_sequence.iter_mut().enumerate() {
                let mut integer = 0u32;
                for index in 0..ops as usize {
                    if (gray >> index) & 1 != 0 {
                        integer ^= self.direction_integers[index][k];
                    }
                }
                *value = integer;
            }
        } else {
            self.integer_sequence.fill(0);
            for (index, row) in self.direction_integers.iter().enumerate() {
                if (n >> index) & 1 != 0 {
                    for (value, &direction) in self.integer_sequence.iter_mut().zip(row) {
                        *value ^= direction;
                    }
                }
            }
        }

        self.sequence_counter = skip;
        &self.integer_sequence
    }

    /// Returns the next sample as raw 32-bit Sobol integers.
    ///
    /// # Panics
    ///
    /// Panics when the sequence counter wraps around ("period exceeded").
    pub fn next_int32_sequence(&mut self) -> &[u32] {
        if !self.use_gray_code {
            self.skip_to(self.sequence_counter);
            if self.first_draw {
                self.first_draw = false;
            } else {
                self.sequence_counter = self
                    .sequence_counter
                    .checked_add(1)
                    .expect("period exceeded");
            }
            return &self.integer_sequence;
        }

        if self.first_draw {
            self.first_draw = false;
            return &self.integer_sequence;
        }

        self.sequence_counter = self
            .sequence_counter
            .checked_add(1)
            .expect("period exceeded");

        let mut n = self.sequence_counter;
        let mut j = 0;
        while n & 1 != 0 {
            n >>= 1;
            j += 1;
        }
        for (value, &direction) in self
            .integer_sequence
            .iter_mut()
            .zip(&self.direction_integers[j])
        {
            *value ^= direction;
        }
        &self.integer_sequence
    }

    /// Returns the next sample normalized to `(0, 1)`.
    pub fn next_sequence(&mut self) -> &[f64] {
        self.next_int32_sequence();
        for (value, &integer) in self.sequence.iter_mut().zip(&self.integer_sequence) {
            *value = f64::from(integer) * (0.5 / 2_147_483_648.0);
        }
        &self.sequence
    }

    /// Returns the last sample normalized to `(0, 1)`.
    pub fn last_sequence(&self) -> &[f64] {
        &self.sequence
    }

    /// Returns the dimensionality of the sequence.
    pub fn dimension(&self) -> usize {
        self.dimensionality
    }
}
