# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "UniformRandomGenerator",
]

@typing.final
class UniformRandomGenerator:
    r"""
    The uniform pseudo-random number generator: a Mersenne Twister (MT19937)
    with period 2^19937 - 1, QuantLib's `MersenneTwisterUniformRng`.

    Draws are deterministic for a non-zero seed: the same seed reproduces the
    same stream bitwise, on every platform. A seed of 0 draws a random seed
    from the core seed generator, so two zero-seeded generators diverge.
    """
    def __init__(self, seed: builtins.int = 0) -> None:
        r"""
        Build a generator from a seed.

        Args:
            seed (int): The 32-bit seed. 0 (the default) draws a random seed
                from the core seed generator, matching QuantLib.
        """
    @staticmethod
    def from_seeds(seeds: typing.Sequence[builtins.int]) -> UniformRandomGenerator:
        r"""
        Build a generator from an array of seeds, the reference
        `init_by_array` initialization.

        Args:
            seeds (list[int]): The 32-bit seed words; at least one.

        Returns:
            UniformRandomGenerator: The generator initialized from the array.

        Raises:
            ItofinError: If seeds is empty.
        """
    def next_real(self) -> builtins.float:
        r"""
        Draw the next uniform deviate.

        Returns:
            float: A deviate strictly inside (0, 1): the raw 32-bit output
            shifted by one half and scaled by 2^-32, so neither endpoint is
            ever returned.
        """
    def next_u32(self) -> builtins.int:
        r"""
        Draw the next raw 32-bit output.

        Returns:
            int: An integer uniform over [0, 2^32 - 1].
        """
    def next_reals(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many uniform deviates in one call.

        Args:
            count (int): The number of deviates to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count,), holding exactly
            what count successive next_real() calls would have returned.

        Raises:
            ItofinError: If a buffer of count draws cannot be allocated.
        """
