# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "GaussianRandomGenerator",
    "UniformRandomGenerator",
    "UniformRandomSequenceGenerator",
]

@typing.final
class GaussianRandomGenerator:
    r"""
    The Gaussian pseudo-random number generator: the polar Box-Muller
    transform over a Mersenne Twister, QuantLib's
    `BoxMullerGaussianRng<MersenneTwisterUniformRng>`.

    Each pair of uniform draws yields two standard normal deviates; the second
    is cached and returned by the next call, as in QuantLib.
    """
    def __init__(self, rng: UniformRandomGenerator) -> None:
        r"""
        Build a generator over a copy of a uniform generator.

        Args:
            rng (UniformRandomGenerator): The uniform generator to copy the
                state from.
        """
    @staticmethod
    def with_seed(seed: builtins.int = 0) -> GaussianRandomGenerator:
        r"""
        Build a generator over a fresh Mersenne Twister.

        Args:
            seed (int): The 32-bit seed; 0 draws a random seed.

        Returns:
            GaussianRandomGenerator: The seeded generator.
        """
    def next_gaussian(self) -> builtins.float:
        r"""
        Draw the next standard normal deviate.

        Returns:
            float: A deviate with mean 0 and standard deviation 1.
        """
    def next_gaussians(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many standard normal deviates in one call.

        Args:
            count (int): The number of deviates to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count,), holding exactly
            what count successive next_gaussian() calls would have returned.

        Raises:
            ItofinError: If a buffer of count draws cannot be allocated.
        """

@typing.final
class UniformRandomGenerator:
    r"""
    The uniform pseudo-random number generator: a Mersenne Twister (MT19937)
    with period 2^19937 - 1, QuantLib's `MersenneTwisterUniformRng`.

    Draws are deterministic for a non-zero seed: the same seed reproduces the
    same stream bitwise, on every platform. A seed of 0 draws a random seed
    from the core seed generator, so two zero-seeded generators diverge.
    """
    def __init__(self, seed: builtins.int = 0) -> None:
        r"""
        Build a generator from a seed.

        Args:
            seed (int): The 32-bit seed. 0 (the default) draws a random seed
                from the core seed generator, matching QuantLib.
        """
    @staticmethod
    def from_seeds(seeds: typing.Sequence[builtins.int]) -> UniformRandomGenerator:
        r"""
        Build a generator from an array of seeds, the reference
        `init_by_array` initialization.

        Args:
            seeds (list[int]): The 32-bit seed words; at least one.

        Returns:
            UniformRandomGenerator: The generator initialized from the array.

        Raises:
            ItofinError: If seeds is empty.
        """
    def next_real(self) -> builtins.float:
        r"""
        Draw the next uniform deviate.

        Returns:
            float: A deviate strictly inside (0, 1): the raw 32-bit output
            shifted by one half and scaled by 2^-32, so neither endpoint is
            ever returned.
        """
    def next_u32(self) -> builtins.int:
        r"""
        Draw the next raw 32-bit output.

        Returns:
            int: An integer uniform over [0, 2^32 - 1].
        """
    def next_reals(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many uniform deviates in one call.

        Args:
            count (int): The number of deviates to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count,), holding exactly
            what count successive next_real() calls would have returned.

        Raises:
            ItofinError: If a buffer of count draws cannot be allocated.
        """

@typing.final
class UniformRandomSequenceGenerator:
    r"""
    The uniform random sequence generator: `dimension` Mersenne-Twister draws
    per sequence, QuantLib's `RandomSequenceGenerator<MersenneTwisterUniformRng>`.

    The generator copies the scalar generator it is built from, as QuantLib
    does, so later draws on the original do not affect the sequence.
    """
    def __init__(self, dimension: builtins.int, rng: UniformRandomGenerator) -> None:
        r"""
        Build a sequence generator over a copy of a scalar generator.

        Args:
            dimension (int): The number of draws per sequence, at least 1.
            rng (UniformRandomGenerator): The scalar generator to copy the
                state from.

        Raises:
            ItofinError: If dimension is 0.
        """
    @staticmethod
    def with_seed(dimension: builtins.int, seed: builtins.int = 0) -> UniformRandomSequenceGenerator:
        r"""
        Build a sequence generator over a fresh Mersenne Twister.

        Args:
            dimension (int): The number of draws per sequence, at least 1.
            seed (int): The 32-bit seed; 0 draws a random seed.

        Returns:
            UniformRandomSequenceGenerator: The seeded sequence generator.

        Raises:
            ItofinError: If dimension is 0.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per sequence.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next sequence.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,), every entry
            strictly inside (0, 1).
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn sequence, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many sequences in one call.

        Args:
            count (int): The number of sequences to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count sequences cannot be allocated.
        """
