"""Runtime source shim for the native ``itofin.models`` submodule.

The real ``itofin.models`` is a compiled submodule registered into
``sys.modules`` by the extension (see crates/itofin-py/src/lib.rs); it wins
at import time, so nothing here runs. This file exists only so static type
checkers resolve ``from itofin.models import ...`` from ``models.pyi`` without
a ``reportMissingModuleSource`` warning.

Auto-generated by scripts/gen_submodule_shims.py from ``models.pyi``; do not edit or delete by hand.
"""
