# Hand-written stubs for itofin.quotes; sync manually with src/market.rs (#517).

class SimpleQuote:
    """A mutable, observable market element (D1)."""

    def __init__(self, value: float) -> None: ...
    def value(self) -> float: ...
    def set_value(self, value: float) -> None: ...
