# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "OptimizeResult",
    "Status",
    "minimize",
]

@typing.final
class OptimizeResult:
    r"""
    The outcome of a minimize run: the best point found and why it stopped.
    """
    @property
    def fun(self) -> builtins.float: ...
    @property
    def nit(self) -> builtins.int: ...
    @property
    def nfev(self) -> builtins.int: ...
    @property
    def njev(self) -> builtins.int: ...
    @property
    def status(self) -> Status: ...
    @property
    def success(self) -> builtins.bool: ...
    @property
    def message(self) -> builtins.str: ...
    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The best point found, as a new float64 array.
        """

@typing.final
class Status:
    r"""
    Why a minimize run stopped.

    The integer values are fixed and append-only, matching the C
    ItofinOptimizeStatus and the Go OptimizeStatus: 8 is reserved for
    a constrained solver.
    """
    ConvergedXTol: typing.ClassVar[Status]
    ConvergedFTol: typing.ClassVar[Status]
    ConvergedGTol: typing.ClassVar[Status]
    MaxIterations: typing.ClassVar[Status]
    MaxEvaluations: typing.ClassVar[Status]
    Cancelled: typing.ClassVar[Status]
    Nonfinite: typing.ClassVar[Status]
    LineSearchFailed: typing.ClassVar[Status]
    def __new__(cls, _unconstructible: typing.NoReturn) -> Status: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

def minimize(fun: typing.Callable[[numpy.typing.NDArray[numpy.float64]], float], x0: typing.Sequence[builtins.float], method: builtins.str = 'Nelder-Mead', options: typing.Optional[dict] = None, callback: typing.Optional[typing.Callable[[numpy.typing.NDArray[numpy.float64]], object]] = None, jac: typing.Optional[typing.Callable[[numpy.typing.NDArray[numpy.float64]], typing.Sequence[float]]] = None, bounds: typing.Optional[typing.Any] = None) -> OptimizeResult:
    r"""
    Minimize a scalar function of one or more variables.

    Args:
        fun (Callable): Called as fun(x) with a float64 array; returns a float.
        x0 (Sequence[float]): The starting point.
        method (str): "Nelder-Mead" or "BFGS" (any case).
        options (dict | None): Nelder-Mead accepts maxiter, maxfev, xatol,
            fatol and adaptive. BFGS accepts maxiter, gtol and eps; other
            keys are rejected.
        callback (Callable | None): Called as callback(xk) after every
            iteration. Raising StopIteration stops the run with
            Status.Cancelled.
        jac (Callable | None): BFGS analytic gradient, called as jac(x).
        bounds: Rejected; neither exposed method supports bounds.

    Returns:
        OptimizeResult: The best point found and why the run stopped.

    Raises:
        ItofinError: On an unknown method or option, or a rejected input.
        Exception: Whatever fun, jac or callback raised, re-raised unchanged.
    """
